version: "3"
services:
  web:
    build: api/
    restart: on-failure
    volumes:
      - ./api/:/usr/src/app/
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./setup-db.sql:/docker-entrypoint-initdb.d/stuff.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=hh
      - POSTGRES_PASSWORD=docker
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/templates:/var/www
    ports:
      - "80:80"
    restart: on-failure
    depends_on:
      - web

volumes:
  db-data:
